// intentional unintended poetry is an interactive experience based on "zombie literature"  created by spam account bots on Weibo,
// a Chinese equivalent of twitter. In most cases, this type of text is the result of random postings by bot accounts with the help
// of algorithms in order to generate fake traffic. These text often show characteristics of logical confusion: random splicing of 
// sentences, mixed use of parts of speech, random characters, misuse of punctuation...Although they are meant to have no "meaning", 
//some of these "poems" generated by bots are accurate manifestations of the postmodernism concept. I've selected and translated
//some popular posts as the centerpieces of intentional unintended poetry. Interact with arrow keys/wasd.
//
//MUSIC:
//The Code of My Heart by gurdonark (c) copyright 2017 Licensed under a Creative Commons Attribution Noncommercial  (3.0) license.
//http://dig.ccmixter.org/files/gurdonark/55904 Ft: Speck
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//variables for player
let xpos = 1100;
let ypos = 600;
let movespd = 10;
let playerwidth = 50;
let playerheight = 50;

//page 1 variables
let text01 = false;
let text02 = false;
let text03 = false;
let bump1 = false;
let bump2 = false;
let bump3 = false;
let page = 0;
let box = false;


//page 2 variables
let text201 = false;
let bump201 = false;

//page 3 variables
let b = 0
let stars = []
let n = 0

//page 4 variables
let text401 = false;
//let bump401 = false;

//page 5 

//page 6 variables
let text601 = false;
let text602 = false;


//page 8 variables
let text801 = false;
let bump801 = false;

//page 9 variables
let video;
const maxXChange = 125;
const maxYChange = 5;
const yNoiseChange = 0.01;
const mouseYNoiseChange = 0.3;
const timeNoiseChange = 0.013;
let timer = 10;



//loading image & sound variables
let page1;
let page2;
let page3;
let page4;
let page5;
let page6;
let page7;
let page8;
let statue;
let ghost;
let e1;
let heartimg;
let music;
let pool;
let exit2;
let umbrella;
let typingsd;
let window1;
let darkghost;
let exit4;
let ladder;
let shark2img;
let shark1img;
let model;
let jayden;
let ghostback;
let moony;
let earth;

function preload(){
	//image
	page1 = loadImage('images/page1-1.png')
	page2 = loadImage('images/page2-1.png')
	page3 = loadImage('images/page3-1.png')
	page4 = loadImage('images/page4-1.png')
	page5 = loadImage('images/page5-1.png')
	page6 = loadImage('images/page6-1.png')
	page7 = loadImage('images/page7-1.png')
	page8 = loadImage('images/page8-1.gif')
	statue = loadImage('images/broken statue.png')
	ghost = loadImage('images/ghost.png')
	pixel = loadFont('font/PressStart2P-Regular.ttf')
	lotus = loadImage('images/lotus.png')
	e1 = loadImage('images/exit1.png')
	heartimg = loadImage('images/heart.png')
	pool = loadImage('images/humanpool.png')
	e2 = loadImage('images/exit2.png')
	e3 = loadImage('images/exit3.png')
	umbrella = loadImage('images/umbrella.png')
	window1 = loadImage('images/window1.png')
	darkghost = loadImage('images/darkghost.png')
	e4 = loadImage('images/exit4.png')
	ladder = loadImage('images/ladder.png')
	flowerl = loadImage('images/flower-l.gif')
	flowerr = loadImage('images/flower-r.gif')
	flower = loadImage('images/flower.gif')
	e5 = loadImage('images/exit5.png')
	e6 = loadImage('images/exit6.png')
	shark2img = loadImage('images/shark2.png')
	shark1img = loadImage('images/shark1.png')
	model = loadImage('images/model.png')
	jayden =  loadImage('images/jayden.png')
	ghostback = loadImage('images/ghostback.png')
	moony = loadImage('images/moony.png')
	earth = loadImage('images/earth.png')
	e8 = loadImage('images/jelly.png')


	
	//sound
	music = loadSound('sound/thecodeofmyheart.mp3')
	typingsd = loadSound("sound/click.wav");
	
	
	
}

function setup() {
	
	frameRate(18);
	createCanvas(1280, 720);
	imageMode(CENTER);
	textAlign(CENTER);
	rectMode(CENTER); 
	noStroke();
	video = createCapture(VIDEO);
	video.size(1000,1000);
	video.hide(); 
	background(0);
	

	
	//instaces on page 1
	obs1 = new obstacle(lotus,700,600,120,120);
	obs2 = new obstacle(lotus,400,350,70,70);
	obs3 = new obstacle(lotus,820,200,50,50);
	exit1 = new exit(645,75,60,60);
	
  //instances on page 2
	heart = new obstacle(heartimg,width/2,300,80,80);
	exit2 = new exit(width/2, 620,130,130);
	for(let i = 0; i<100; i++){
    stars[i] = new star(random(width),random(height),random(-PI,PI),random(0.1,2));

  }
	//instances on page 3
	exit3 = new exit(100,80,80,80);
	
	//instances on page 4
	puddle = new obstacle(pool,1000,550,300,300);
	exit4 = new exit(1150,100,200,200);

	//instances on page 5
	exit5 = new exit(1070,620,384,200);

	//instances on page 6
	shark1 = new obstacle(shark1img,400,500,300,300);
	shark2 = new obstacle(shark2img,900,500,300,300);
	exit6 = new exit(30,23,94,46);

	//instances on page 7
	exit7 = new exit(1100,600,100,100);

	//instances on page 8
	someone = new obstacle(ghostback,width/2,600,67,80);
	exit8 = new exit(120,150,250,250);



}



function draw() {
	//function for faster access to pages when testing
	testing();
	
	imgcontrol();	
	
	//sounds();
	//call usercollide function
	userCollide();
	if (page == 0){
		start();
		if (keyIsDown(ENTER)){
			if (music.isPlaying() == false){
			music.setVolume(0.3);
			music.play();
			music.loop();
		   }
		}
	}
	//if page is one, display instances on page one, "lotus and buddha"
	if (page == 1){
		image(ghost,xpos,ypos,80,80);
		obs1.display();
		obs2.display();
		obs3.display();
		exit1.display();
		if (box !=false){
			fill(0);
			rect(width/2,height/2,600,200);
		}	
		//text appears depends on which object player collides with
		if (text01 == true){
		//calling type function which creates a character by character typing effect
			type('The natural disasters, meteorites,\n\nUFOs, nuclear explosions, doomsday,\n\nsolar storms, wars, and diseases\n\nthat I bought before Christmas...',width/2,310);
		}
		if (text02 == true){
			type('I will call them to delay\n\nthe delivery...\n\nMy heart is beating,\n\nthe entire world has changed...',width/2,310);
		}
		if (text03 == true){
			type('because of your appearance.',width/2,height/2);
		}
	}


	//displays objects on page 2, "heartbreak"
	if (page == 2){
		image(ghost,xpos,ypos,80,80);
		heart.display();
		exit2.display();
		if (box !=false){
			fill(0);
			rect(width/2,height/2,800,200);
		}	
		if (text201 == true){
			type("Later, I found that you belong to the gazes\n\nof every eye...So I love you more; and then I\n\nfound that no one could ever possess you,\n\nso I love you no more.",width/2, height/2-45);
		}
	}
	
	//displays objects on page 3, "floating stars"
	if (page == 3){
		image(darkghost,xpos,ypos,80,80);
		for (let i = 0; i < stars.length; i++){
    stars[i].display();
		stars[i].move();
  	}
		exit3.display();
		exit3.move3();
		fill(0);
		rect(width/2,height/2,700,150);
		type("I loved you for so long without a reason!\n\nStars...",width/2,height/2-10)
	}
	
	//displays objects on page 4，"human shaped pool"
    if (page == 4){
		puddle.display();
		exit4.display();
		image(umbrella,xpos,ypos,80,80);
		if (box !=false){
			fill(0);
			rect(width/2,height/2,800,200);
		}	
		if (text401 == true){
			type("It would be a bit scary if it really\n\nwere a pool of clear water.\n\nBut the world is so crowded...\n\nmother.",width/2, height/2-48);
		}
	}

	//displays objects on page 5, "ladder to home"

    if (page == 5){
		exit5.display();
		image(flowerr,120,50,198,254.5);
		//image(flowerl,1200,50);
		image(ladder,1100,100);
		image(flower,width/2-40,580);
		image(flower,50,820);
    	image(ghost,xpos,ypos,80,80);
		image(flowerl,1200,50);
		fill(0);
		rect(width/2,height/2,600,150);
		type("The road to home...\n\nThe road to home...",width/2,height/2-10)
    }
    
	//displays objects on page 6, "shark museum"
    if (page == 6){
		shark1.display();
		shark2.display();
		exit6.display();
		image(jayden,915,410,210,65)
		push();
		//translate(width / 2, height / 2);
		rotate(PI / 3.5);
		image(model,640,-50,83.3,207.7)
		pop();
		image(ghost,xpos,ypos,80,80);
		if (box !=false){
			fill(0);
			rect(width/2,height/2,600,150);
		}
		if (text602 == true){
			type("You want me to turn back.\n\nIt is my choice;",width/2,height/2-10)
		}
		if (text601 == true){
			type("You are shouting by the sea,\n\ndrowning me\n\nover and over again.",width/2,height/2-30)
		}
	}
	
	//displays objects on page 7, "hide and seek"
	if (page == 7){
		exit7.display();
		image(ghost,xpos,ypos,80,80);
		image(page7,width/2,height/2,1280,720);
	}


	//displays objects on page 8, "moony"
	if (page==8){
		image(earth,width/2,height/2,1280,720);
		image(moony,width/2,-50,1200,1200);
		image(e8,220,10,150,150)
		someone.display();
		exit8.display();
		image(ghost,xpos,ypos,80,80);
		if (box !=false){
			fill(0);
			rect(width/2,height/2,600,150);
		}
		if (text801 == true){
			type("Die for us! Flying away;\n\nliving until\n\nthere is nothing left",width/2,height/2-30)
		}
	}


	//displays effects on page 9, "face your reality"
	if (page == 9){
		for (let i = 0; i < video.height/60; i++) {
			drawStreak()
		}
		fill(0);
		rect(width/10-30,height/2,200,height);
		rect(width-100,height/2,200,height);
		rect(width/2,height/2,600,150);
		type("...once awakened,\n\nit is but\n\nan illusion that vanishes.",width/2,height/2-30);
		countdown();
		//console.log(timer);
	}

	//credits/ending page
	if (page == 10){
		background(0);
		type("intentional unintended poetry\n\nby phoebe yin",width/2,height/2);
		timer = 10;
		
	}
	console.log(page)
}