// intentional unintended poetry is an interactive experience based on "zombie literature"  created by spam account bots on Weibo,
// a Chinese equivalent of twitter. In most cases, this type of text is the result of random postings by bot accounts with the help
// of algorithms in order to generate fake traffic. These text often show characteristics of logical confusion: random splicing of 
// sentences, mixed use of parts of speech, random characters, misuse of punctuation...Although they are meant to have no "meaning", 
//some of these "poems" generated by bots are accurate manifestations of the postmodernism concept. I've selected and translated
//some popular posts as the centerpieces of intentional unintended poetry. Interact with arrow keys/wasd.


let xpos = 900;
let ypos = 550;
let movespd = 1;
let playerwidth = 50;
let playerheight = 50;
let text01 = 0
let text02 = 0
let text03 = 0
let page = 1
let b = 0
let stars = []
let n = 0



function setup() {
	frameRate(15);
	createCanvas(1000, 600);
	textAlign(CENTER);
	rectMode(CENTER); 
	noStroke();
	//instaces on page 1
	obs1 = new obstacle(500,550,50,50)
	obs2 = new obstacle(200,300,50,50)
	obs3 = new obstacle(700,200,50,50)
	exit1 = new exit(500,20,30,30)
	
  //instances on page 2
	heart = new obstacle(width/2,200,60,60)
	exit2 = new exit(width/2, 500,10,10)
	for(let i = 0; i<100; i++){
    stars[i] = new star(random(width),random(height),random(-PI,PI),random(0.1,1.2));

  }
	//instances on page 3
	exit3 = new exit(100,80,30,30)
	
	//instances on page 4
	puddle = new obstacle(800,550,120,50)
}


function draw() {
	background(100);
	//call player function
	player();
	//if page is one, display instances on page one
	if (page == 1){
		obs1.display();
		obs2.display();
		obs3.display();
		exit1.display();
		//text appears depends on which object player collides with
		if (text01 == 1){
		//calling type function which creates a character by character typing effect
			type('this is the first line of\nthe poem',width/2,300)
		}else if (text01 == 2){
		//problem: cannot get it to work again
			type('line2 of the poem \n hahah', width/2,300);
		}else if (text01 == 3){
			type('line3',width/2,300);
		}
	}
	//displays objects on page 2
	if (page == 2){
		heart.display();
		exit2.display();
		if (text02 == 1){
			text("second poem first part",width/2, height/2 +100);
		}
	}
	//displays objects on page 3
	if (page == 3){
		for (let i = 0; i < stars.length; i++){
    stars[i].display();
		stars[i].move();
  	}
		exit3.display();
		text("second poem second part",width/2,height/2)
	}
	
	//displays objects on page 4
  if (page == 4){
		puddle.display();
		if (text03 == 1){
			text("third poem",width/2, height/2 +100);
		}
	}
	console.log(n)
	
	
}